In [3]:
!pip install yfinance

Collecting yfinance
  Using cached yfinance-0.2.33-py2.py3-none-any.whl (69 kB)
Requirement already satisfied: pytz>=2022.5 in c:\anaconda3\lib\site-packages (from yfinance) (2022.7)
Collecting multitasking>=0.0.7
  Using cached multitasking-0.0.11-py3-none-any.whl (8.5 kB)
Requirement already satisfied: requests>=2.31 in c:\anaconda3\lib\site-packages (from yfinance) (2.31.0)
Requirement already satisfied: numpy>=1.16.5 in c:\anaconda3\lib\site-packages (from yfinance) (1.23.5)
Collecting frozendict>=2.3.4
  Using cached frozendict-2.4.0-cp310-cp310-win_amd64.whl (36 kB)
Collecting html5lib>=1.1
  Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
     ------------------------------------ 112.2/112.2 kB 251.1 kB/s eta 0:00:00
Requirement already satisfied: lxml>=4.9.1 in c:\anaconda3\lib\site-packages (from yfinance) (4.9.1)
Collecting peewee>=3.16.2
  Downloading peewee-3.17.0.tar.gz (2.9 MB)
     ---------------------------------------- 2.9/2.9 MB 95.5 kB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\anaconda3\lib\site-packages (from yfinance) (4.11.1)
Requirement already satisfied: pandas>=1.3.0 in c:\anaconda3\lib\site-packages (from yfinance) (1.5.3)
Requirement already satisfied: appdirs>=1.4.4 in c:\anaconda3\lib\site-packages (from yfinance) (1.4.4)
Requirement already satisfied: soupsieve>1.2 in c:\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.3.2.post1)
Requirement already satisfied: six>=1.9 in c:\anaconda3\lib\site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in c:\anaconda3\lib\site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2.0.5)
Requirement already satisfied: idna<4,>=2.5 in c:\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2022.12.7)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2.0.4)
Building wheels for collected packages: peewee
  Building wheel for peewee (pyproject.toml): started
  Building wheel for peewee (pyproject.toml): finished with status 'done'
  Created wheel for peewee: filename=peewee-3.17.0-py3-none-any.whl size=135766 sha256=5e0d3fc9b707ac492f835d399df89db9e1484f6c1760b4d023001a3ac9b9fe4b
  Stored in directory: c:\users\91882\appdata\local\pip\cache\wheels\e2\b9\da\716514851b65304b2d24f2a161398b9470da589b08a5a586c8
Successfully built peewee
Installing collected packages: peewee, multitasking, html5lib, frozendict, yfinance
Successfully installed frozendict-2.4.0 html5lib-1.1 multitasking-0.0.11 peewee-3.17.0 yfinance-0.2.33

In [5]:
!pip install ccxt

Collecting ccxt
  Downloading ccxt-4.2.4-py2.py3-none-any.whl (4.0 MB)
     ---------------------------------------- 4.0/4.0 MB 225.9 kB/s eta 0:00:00
Requirement already satisfied: requests>=2.18.4 in c:\anaconda3\lib\site-packages (from ccxt) (2.31.0)
Collecting aiohttp>=3.8
  Downloading aiohttp-3.9.1-cp310-cp310-win_amd64.whl (364 kB)
     ------------------------------------ 364.6/364.6 kB 241.3 kB/s eta 0:00:00
Requirement already satisfied: cryptography>=2.6.1 in c:\anaconda3\lib\site-packages (from ccxt) (39.0.1)
Requirement already satisfied: typing-extensions>=4.4.0 in c:\anaconda3\lib\site-packages (from ccxt) (4.4.0)
Collecting yarl>=1.7.2
  Downloading yarl-1.9.4-cp310-cp310-win_amd64.whl (76 kB)
     -------------------------------------- 76.4/76.4 kB 212.1 kB/s eta 0:00:00
Requirement already satisfied: setuptools>=60.9.0 in c:\anaconda3\lib\site-packages (from ccxt) (65.6.3)
Collecting aiodns>=1.1.1
  Downloading aiodns-3.1.1-py3-none-any.whl (5.4 kB)
Requirement already satisfied: certifi>=2018.1.18 in c:\anaconda3\lib\site-packages (from ccxt) (2022.12.7)
Collecting pycares>=4.0.0
  Downloading pycares-4.4.0-cp310-cp310-win_amd64.whl (76 kB)
     -------------------------------------- 76.3/76.3 kB 248.2 kB/s eta 0:00:00
Requirement already satisfied: attrs>=17.3.0 in c:\anaconda3\lib\site-packages (from aiohttp>=3.8->ccxt) (22.1.0)
Collecting async-timeout<5.0,>=4.0
  Using cached async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
Collecting aiosignal>=1.1.2
  Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.4.1-cp310-cp310-win_amd64.whl (50 kB)
     -------------------------------------- 50.4/50.4 kB 368.8 kB/s eta 0:00:00
Collecting multidict<7.0,>=4.5
  Downloading multidict-6.0.4-cp310-cp310-win_amd64.whl (28 kB)
Requirement already satisfied: cffi>=1.12 in c:\anaconda3\lib\site-packages (from cryptography>=2.6.1->ccxt) (1.15.1)
Requirement already satisfied: idna<4,>=2.5 in c:\anaconda3\lib\site-packages (from requests>=2.18.4->ccxt) (3.4)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\anaconda3\lib\site-packages (from requests>=2.18.4->ccxt) (2.0.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\anaconda3\lib\site-packages (from requests>=2.18.4->ccxt) (2.0.5)
Requirement already satisfied: pycparser in c:\anaconda3\lib\site-packages (from cffi>=1.12->cryptography>=2.6.1->ccxt) (2.21)
Installing collected packages: multidict, frozenlist, async-timeout, yarl, pycares, aiosignal, aiohttp, aiodns, ccxt
Successfully installed aiodns-3.1.1 aiohttp-3.9.1 aiosignal-1.3.1 async-timeout-4.0.3 ccxt-4.2.4 frozenlist-1.4.1 multidict-6.0.4 pycares-4.4.0 yarl-1.9.4

In [1]:
import yfinance as yf

In [9]:
btc = yf.Ticker('BTC-USD')
prices1 = btc.history(period='8y')

In [10]:
prices1

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2016-01-10 00:00:00+00:00,448.238007,448.308990,440.351013,447.990997,35995900,0.0,0.0
2016-01-11 00:00:00+00:00,448.697998,450.661987,443.855011,448.428009,40450000,0.0,0.0
2016-01-12 00:00:00+00:00,448.182007,448.182007,435.690002,435.690002,115607000,0.0,0.0
2016-01-13 00:00:00+00:00,434.665009,435.186005,424.442993,432.371002,173888000,0.0,0.0
2016-01-14 00:00:00+00:00,432.287994,433.324005,427.845001,430.306000,43945500,0.0,0.0
...,...,...,...,...,...,...,...
2024-01-06 00:00:00+00:00,44178.953125,44227.632812,43475.156250,43989.195312,16092503468,0.0,0.0
2024-01-07 00:00:00+00:00,43998.464844,44495.570312,43662.230469,43943.097656,19330573863,0.0,0.0
2024-01-08 00:00:00+00:00,43948.707031,47218.000000,43244.082031,46970.503906,42746192015,0.0,0.0
2024-01-09 00:00:00+00:00,46987.640625,47893.699219,45244.714844,46139.730469,39821290992,0.0,0.0
2024-01-10 00:00:00+00:00,46121.539062,46624.394531,44707.554688,46509.925781,45318402048,0.0,0.0

In [11]:
usdt = yf.Ticker('USDT-USD')
prices2 = usdt.history(period='5y')

In [12]:
data=prices1.join(prices2, lsuffix = ' (BTC)', rsuffix = ' (USDT)')

In [13]:
data

,Open (BTC),High (BTC),Low (BTC),Close (BTC),Volume (BTC),Dividends (BTC),Stock Splits (BTC),Open (USDT),High (USDT),Low (USDT),Close (USDT),Volume (USDT),Dividends (USDT),Stock Splits (USDT)
Date,,,,,,,,,,,,,,
2016-01-10 00:00:00+00:00,448.238007,448.308990,440.351013,447.990997,35995900,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-01-11 00:00:00+00:00,448.697998,450.661987,443.855011,448.428009,40450000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-01-12 00:00:00+00:00,448.182007,448.182007,435.690002,435.690002,115607000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-01-13 00:00:00+00:00,434.665009,435.186005,424.442993,432.371002,173888000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-01-14 00:00:00+00:00,432.287994,433.324005,427.845001,430.306000,43945500,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-01-06 00:00:00+00:00,44178.953125,44227.632812,43475.156250,43989.195312,16092503468,0.0,0.0,1.000853,1.001393,1.000296,1.000592,3.253218e+10,0.0,0.0
2024-01-07 00:00:00+00:00,43998.464844,44495.570312,43662.230469,43943.097656,19330573863,0.0,0.0,1.000503,1.001211,1.000161,1.000607,3.266686e+10,0.0,0.0
2024-01-08 00:00:00+00:00,43948.707031,47218.000000,43244.082031,46970.503906,42746192015,0.0,0.0,1.000714,1.001379,1.000161,1.000599,6.190602e+10,0.0,0.0
2024-01-09 00:00:00+00:00,46987.640625,47893.699219,45244.714844,46139.730469,39821290992,0.0,0.0,1.000843,1.000980,0.999423,1.000166,6.139698e+10,0.0,0.0
2024-01-10 00:00:00+00:00,46121.539062,46624.394531,44707.554688,46509.925781,45318402048,0.0,0.0,1.000235,1.000904,1.000003,1.000436,7.106337e+10,0.0,0.0

In [14]:
start_date = '2018-01-01'
end_date = '2022-01-31'

In [15]:
filtered_data = data[(data.index >= start_date) & (data.index <= end_date)]

In [16]:
filtered_data

,Open (BTC),High (BTC),Low (BTC),Close (BTC),Volume (BTC),Dividends (BTC),Stock Splits (BTC),Open (USDT),High (USDT),Low (USDT),Close (USDT),Volume (USDT),Dividends (USDT),Stock Splits (USDT)
Date,,,,,,,,,,,,,,
2018-01-01 00:00:00+00:00,14112.200195,14112.200195,13154.700195,13657.200195,10291200000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-02 00:00:00+00:00,13625.000000,15444.599609,13163.599609,14982.099609,16846600192,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-03 00:00:00+00:00,14978.200195,15572.799805,14844.500000,15201.000000,16871900160,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-04 00:00:00+00:00,15270.700195,15739.700195,14522.200195,15599.200195,21783199744,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-05 00:00:00+00:00,15477.200195,17705.199219,15202.799805,17429.500000,23840899072,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-01-27 00:00:00+00:00,36841.878906,37148.324219,35629.281250,37138.234375,25041426629,0.0,0.0,1.000632,1.000859,1.000207,1.000344,5.395093e+10,0.0,0.0
2022-01-28 00:00:00+00:00,37128.445312,37952.878906,36211.109375,37784.332031,22238830523,0.0,0.0,1.000343,1.000723,1.000151,1.000345,5.068826e+10,0.0,0.0
2022-01-29 00:00:00+00:00,37780.714844,38576.261719,37406.472656,38138.179688,17194183075,0.0,0.0,1.000340,1.000633,1.000194,1.000362,3.935719e+10,0.0,0.0
2022-01-30 00:00:00+00:00,38151.917969,38266.339844,37437.710938,37917.601562,14643548444,0.0,0.0,1.000455,1.000607,1.000234,1.000341,3.504371e+10,0.0,0.0
2022-01-31 00:00:00+00:00,37920.281250,38647.261719,36733.574219,38483.125000,20734730465,0.0,0.0,1.000344,1.000677,1.000265,1.000485,4.508269e+10,0.0,0.0

In [17]:
data.to_csv('crypto.csv')